### ISSUE TITLE
Таски для версии сайта 3.0.4

### ISSUE THREAD

**Issue by KeyJoo** [KeyJoo/baraban16#38]
- [x] Убрать 3 цветные кнопки (опилки) #40
- [x] Поменять местами фото в галереи  #39
- [x] Заменить текст на всей странице #41
